### PR TITLE
Add redirection link and README

### PR DESCRIPTION
**Pull request by d-siganos**
It sometimes happens and the user is not redirected to the website. So, I have added a link to the website just in case the redirection does not work, along with a `README.md` file for good practice.

### CODE REVIEW

**Comment by micahlt** [comment]
@BonfireScratch Thanks for the pull!  I'm going to add an HTML redirect as well as the JavaScript one, just for accessibility.  Also, do we want to link to the SC4 landing page or directly to the dev beta?

**Comment by icarusinthewings** [comment]
> @BonfireScratch Thanks for the pull! I'm going to add an HTML redirect as well as the JavaScript one, just for accessibility. Also, do we want to link to the SC4 landing page or directly to the dev beta?

I think it should redirect.

**Comment by micahlt** [comment]
@ConvexPolygon no, the question was do we want to redirect to https://sc4.micahlindley.com or https://dev.sc4.micahlindley.com .

**Review by micahlt — APPROVED** [review]
Looks good to me!

**Comment by micahlt** [comment]
@ConvexPolygon I'm good with merging.  I'll commit once you approve the PR.

**Pull request merged**
